name: Test Suite
env:
  DB_URL: ${{ secrets.DB_URL }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run unit tests
        run: yarn unit-test
      - name: Run integration tests
        run: yarn integration-test
      - name: Run all tests
        run: yarn test
